[program:xvfb]
command=/usr/bin/Xvfb :99 -screen 0 %(ENV_SCREEN_GEOMETRY)s -ac +extension GLX +render -noreset
autorestart=true
priority=10
stdout_logfile=/var/log/supervisor/xvfb.log
stderr_logfile=/var/log/supervisor/xvfb.err

[program:x11vnc]
command=/usr/bin/x11vnc -display :99 -nopw -forever -shared -rfbport %(ENV_VNC_PORT)s
autorestart=true
priority=20
stdout_logfile=/var/log/supervisor/x11vnc.log
stderr_logfile=/var/log/supervisor/x11vnc.err

[program:aimm]
command=/usr/local/bin/aimm --webui --webui-host %(ENV_AIMM_WEBUI_HOST)s --webui-port %(ENV_AIMM_WEBUI_PORT)s --webui-base-path %(ENV_AIMM_WEBUI_BASE_PATH)s
environment=DISPLAY=":99"
autorestart=true
priority=40
stdout_logfile=/var/log/supervisor/aimm.log
stderr_logfile=/var/log/supervisor/aimm.err
